// ═══════════════════════════════════════════════════════════════════
// KONFIGURATION — Punkte-Formel, Zeiten, Satz- und Wörter-Pool
// ═══════════════════════════════════════════════════════════════════

export const ROUND_TIME_MS = 30000;
export const PLAYER_COLORS = ['p1','p2','p3','p4','p5','p6','p7','p8'];
export const NUM_ROUNDS = 10;

export function calcPoints({ correct, total, errors, usedMs, maxMs }) {
  if (total === 0) return 0;
  const accuracy = correct / total;
  if (accuracy < 0.5) return 0;
  const accFactor = Math.pow(accuracy, 2);
  const speedFactor = 0.5 + 0.5 * Math.max(0, 1 - (usedMs / maxMs));
  let pts = Math.round(1000 * accFactor * speedFactor);
  if (errors === 0 && accuracy === 1) pts += 200;
  return Math.max(0, pts);
}

// 425 Sätze (≤80 Zeichen, ohne Bindestriche)
export const SENTENCE_POOL = [
"Ich bin nicht faul, ich spare nur meine Energie für wichtige Dinge.",
"Ohne Kaffee bin ich ein Mensch ohne Eigenschaften.",
"Das Leben ist zu kurz für schlechten Wein und gute Diäten.",
"Wer früh aufsteht, ist einfach nur früh müde.",
"Der frühe Vogel kann mich mal.",
"Ich bin nicht arrogant, ich bin nur besser als du.",
"Mein Kalender hat mehr freie Tage als mein Chef erlaubt.",
"Wenn das Leben Zitronen gibt, frag, wo der Tequila ist.",
"Wer lacht, hat noch keine Rechnung aufgemacht.",
"Diäten fangen immer montags an und enden am Dienstag.",
"Ich habe keine Fehler, nur Charakterzüge.",
"Der Kühlschrank ist das einzige, das mich wirklich versteht.",
"Erwachsen werden ist die größte Falle der Kindheit.",
"Ich könnte Sport machen, aber das Sofa hat mich so lieb.",
"Wer nichts weiß, muss alles glauben.",
"Das Internet hat die Dummheit nicht erfunden, nur beschleunigt.",
"Ich habe nichts gegen Arbeit, wir ignorieren uns gegenseitig.",
"Wenn Stille Gold ist, bin ich pleite.",
"Ich bin kein Morgenmuffel, ich bin ein Nachtmensch mit Tagschicht.",
"Ich trinke Kaffee, um Menschen zu ertragen.",
"Wer anderen eine Grube gräbt, braucht einen Bagger.",
"Ich bin spontan geplant.",
"Der Unterschied zwischen Genie und Wahnsinn ist der Erfolg.",
"Mein Handy hat mehr Batterielaufzeit als ich.",
"Stress ist, wenn man alles auf einmal tun will, aber eigentlich nichts.",
"Ein gutes Buch ersetzt hundert Therapiestunden.",
"Wer viel redet, sagt manchmal auch etwas Kluges.",
"Meine Küche kennt nur zwei Gerichte: Bestellen und Aufwärmen.",
"Ich schlafe nicht, ich lade mich auf.",
"Wer braucht einen Therapeuten, wenn er einen Hund hat?",
"Ich bin nicht kompliziert, nur tiefgründig missverstanden.",
"Zähne putzen ist Yoga für den Mund.",
"Ich bin kein Pessimist, ich bin ein enttäuschter Optimist.",
"Mein Gehirn funktioniert wie ein Browser: 47 Tabs offen, 3 hängen.",
"Ich spreche fließend Sarkasmus.",
"Wer gut schläft, hat ein reines Gewissen oder ein gutes Bett.",
"Wer nie scheitert, hat nie etwas Interessantes versucht.",
"Ich bin nicht unfreundlich, ich habe nur ein neutrales Gesicht.",
"Ich spare Energie: Ich denke heute nicht, was ich morgen nicht brauche.",
"Mein Haustier versteht mich besser als mein Chef.",
"Wer lächelt, hat entweder gute Nachrichten oder schlechte Zähne.",
"Das Beste am Montag ist der Dienstag.",
"Wer den Schaden hat, braucht für den Spott nicht zu sorgen.",
"Ich bin kein Nachtschwärmer, ich bin ein Tagverweigerer.",
"Ich bin nicht launisch, ich habe dynamische Stimmungen.",
"Das Beste an einem langen Tag ist das Ende.",
"Wer nichts riskiert, langweilt sich garantiert.",
"Mein Kühlschrank ist ein Museum der vergessenen Lebensmittel.",
"Ohne Kaffee bin ich ein leeres Dokument.",
"Wer immer lächelt, hat entweder alles oder nichts zu verlieren.",
"Das Leben sendet selten Rechnungen mit Rückgaberecht.",
"Träume sind Gebühren für den Tiefschlaf.",
"Der einzige Workout, den ich konsequent mache, ist Augenrollen.",
"Wer nie lügt, ist entweder heilig oder stumm.",
"Meine größte Stärke ist, Probleme zu ignorieren, bis sie verschwinden.",
"Ich bin kein Frühaufsteher, ich bin ein Spätgenießer.",
"Das Beste an Fehlern ist, dass man sie Lernerfahrungen nennen kann.",
"Wer alles kann, macht nichts ordentlich.",
"Ich bin nicht müde, ich bin im Ruhemodus.",
"Wer schweigt, hat entweder nichts zu sagen oder zu viel.",
"Das Sofa hat eine Anziehungskraft, die Physiker noch nicht erklärt haben.",
"Ich bin kein Workaholic, ich vermeide nur die Stille.",
"Das Schönste am Wochenende ist der Samstag nach dem Freitag.",
"Mein Handy weiß mehr über mich als mein bester Freund.",
"Wer gut organisiert ist, war nie wirklich kreativ.",
"Ich schlafe auf Problemen, weil Lösungen manchmal Zeit brauchen.",
"Wer kein Ziel hat, kann auch nicht scheitern.",
"Das Beste an Montagen ist, dass man sie hinter sich bringen kann.",
"Ich pflege meinen Humor täglich, er braucht mehr Pflege als ich.",
"Mein Kopfkissen kennt mehr Geheimnisse als mein Tagebuch.",
"Wer nichts tut, macht auch nichts falsch.",
"Wer klagt, hat keine Zeit zum Handeln.",
"Mein größtes Talent: Ausreden produzieren.",
"Das Beste an der Gegenwart ist, dass sie bald Vergangenheit ist.",
"Ich bin kein Zauderer, ich prüfe nur gründlich.",
"Mein Sofa und ich haben eine ernsthafte Beziehung.",
"Wer nicht fragt, bekommt auch keine Rückmeldung.",
"Ich gehe früh schlafen, damit ich früh fertig bin mit Aufstehen.",
"Mein Telefon hat mehr Freunde als ich.",
"Wer viel grübelt, schläft schlecht.",
"Ich bin kein Optimist, aber ich überlebe jeden Montag.",
"Wer keine Fehler macht, lernt auch nichts.",
"Das Beste am Chaos ist, dass man immer etwas Neues findet.",
"Wer denkt, er hat alles im Griff, hält meistens nichts fest.",
"Wer aufgibt, macht Platz für andere.",
"Das Wetter versteht mich: es ist auch unbeständig.",
"Wer keine Angst kennt, war noch nicht beim Zahnarzt.",
"Das Sofa ist mein Co-Pilot im Leben.",
"Das Leben ist zu kurz für Erklärungen ohne Ende.",
"Wer früh übt, macht früh Fehler.",
"Das Leben ist schön, wenn man nicht zu genau hinschaut.",
"Ich halte Ordnung für ein theoretisches Konzept.",
"Wer Pläne macht, gibt Gott Anlass zum Lachen.",
"Das Beste am Regen ist der Geruch danach.",
"Wer immer Recht hat, langweilt sich.",
"Wer lächelt, hat manchmal keine Ahnung, was er sonst tun soll.",
"Das Beste an Problemen ist, wenn sie jemand anderes hat.",
"Wer sich nicht ärgert, hat nichts zu verlieren.",
"Wer nichts sagt, hat manchmal am meisten gesagt.",
"Ich bin nicht seltsam, ich bin limitiert aufgelegt.",
"Das Beste am Montag ist, dass er nur einmal pro Woche kommt.",
"Wer zu viel verspricht, hat zu wenig nachgedacht.",
"Ich brauche keinen Plan B, wenn Plan A noch nicht angefangen hat.",
"Ich bin spontan, wenn ich genug Zeit hatte, mich vorzubereiten.",
"Wer denkt, er sei der Klügste im Raum, ist meistens allein.",
"Das Beste am Schweigen ist, dass es kostenlos ist.",
"Wer nicht verliert, spielt nicht.",
"Ich brauche keine Perfektion, nur einen funktionierenden Drucker.",
"Wer zu viel denkt, schläft schlecht.",
"Das Beste am Alter ist, dass man es ignorieren kann.",
"Ich bin kein Versager, ich bin ein Langzeitlerner.",
"Wer viele Pläne hat, hat wenig Zeit zum Umsetzen.",
"Ich schlafe auf Problemen, bis sie Lösungen werden.",
"Das Beste am Scheitern ist, dass man danach klüger klingt.",
"Wer Grenzen setzt, schützt sich und nervt die anderen.",
"Ich bin kein Faulpelz, ich betreibe aktives Nichtstun.",
"Das Beste am Herbst sind die Farben und die Ausreden, drinzubleiben.",
"Wer alles gleichzeitig macht, macht alles halb.",
"Ich mache mir keine Illusionen, nur Pläne.",
"Ich bin nicht ungeduldig, ich habe nur wenig Zeit für Langsames.",
"Das Beste am Fehler ist, dass er gemacht ist.",
"Ich bin nicht geschwätzig, ich teile einfach viel mit.",
"Ich bin kein Grübler, ich bin ein strategischer Nachdenker.",
"Wer seinen Fehler zugibt, ist entweder mutig oder erwischt worden.",
"Ich bin kein Choleriker, ich habe nur lebhafte Reaktionen.",
"Das Leben schreibt Dinge, die kein Autor erfinden würde.",
"Wer trauert, liebt noch.",
"Wer glücklich ist, fragt nicht, warum.",
"Das Beste am Wochenende ist, dass es irgendwann kommt.",
"Ich sage oft wenig und meine viel.",
"Ich bin kein Frühaufsteher, aber ein Spätschläfer bin ich auch nicht mehr.",
"Das Beste am Montag ist, dass man ihn bald vergessen kann.",
"Wer denkt, alles zu wissen, hört auf zu lernen.",
"Das Leben ist lauter als gedacht und leiser als gehofft.",
"Wer immer zustimmt, hat keine eigene Meinung.",
"Das Beste an Problemen ist, wenn sie sich selbst lösen.",
"Wer viel erklärt, hat oft zu wenig gemacht.",
"Wer alles plant, hat keine Zeit für Abenteuer.",
"Das Beste am Scheitern ist, dass man Applaus für Mut bekommt.",
"Wer Humor hat, hat eine bessere Abwehr.",
"Das Leben liebt es, wenn man Pläne macht.",
"Wer viel spricht, sagt manchmal nichts.",
"Das Beste an langen Wochenenden ist die Mitte.",
"Ich bin kein Griesgram, ich habe nur einen differenzierten Blick auf den Montag.",
"Wer Grenzen überschreitet, findet manchmal Neues.",
"Das Beste am Chaos ist, dass man nicht aufräumen muss.",
"Wer alles ernst nimmt, hat keinen Spaß.",
"Ich bin kein Weltverbesserer, aber ich halte die Tür auf.",
"Wer nicht irrt, hat noch nicht genug ausprobiert.",
"Das Beste an der Arbeit ist das Feierabend.",
"Wer immer höflich ist, hat einiges zurückgehalten.",
"Das Leben schickt Prüfungen ohne Ankündigung.",
"Das Beste am Frühling ist, dass der Winter vorbei ist.",
"Wer mit sich selbst im Reinen ist, braucht keine Bestätigung.",
"Wer immer Nein sagt, spart sich viel Aufwand.",
"Das Beste an einem guten Buch ist, dass die Welt sich nicht beschwert.",
"Wer lächelt, macht die Welt um 10 Prozent heller.",
"Ich schlafe gut, seit ich aufgehört habe, mich selbst zu verstehen.",
"Das Beste an einem Problem ist, wenn man es löst.",
"Das Beste an einem Nickerchen ist das Aufwachen danach.",
"Wer nie zweifelt, denkt nicht genug nach.",
"Wer nie Nein sagt, hat zu viel auf dem Teller.",
"Das Beste am Scheitern ist, dass man was zu erzählen hat.",
"Wer immer positiv denkt, ignoriert manchmal die Realität.",
"Das Leben ist manchmal ein Umweg, der sich lohnt.",
"Wer rechtzeitig kommt, muss warten.",
"Das Beste am Regen ist, dass man guten Gewissens drinbleibt.",
"Wer immer Ja sagt, hat keine Freizeit mehr.",
"Das Leben vergibt, aber manchmal erst nach Jahren.",
"Ich habe keine Angst vor Fehlern, nur vor dem Wiederholen.",
"Das Beste an einer langen Pause ist, dass man danach wieder kann.",
"Ich schlafe lieber eine Runde mehr als eine weniger.",
"Das Beste an einem Dienstag ist, dass er kein Montag ist.",
"Wer gut erklärt, versteht oft selbst erst dann.",
"Das Beste am Donnerstag ist, dass der Freitag folgt.",
"Ich bin kein Optimist, aber ich glaube an den nächsten Kaffee.",
"Wer nicht zweifelt, glaubt alles.",
"Das Leben ist kein Wunschzettel, aber ich schreibe trotzdem einen.",
"Das Beste an Fehlern ist, dass sie meistens behebbar sind.",
"Wer viel reist, vermisst die Couch.",
"Das Leben macht Witze auf Kosten der Planung.",
"Wer gut schläft, hat die halbe Miete.",
"Das Beste am Donnerstag ist, dass er der neue Freitag ist.",
"Ich bin kein Angeber, ich teile nur Fakten über mich.",
"Wer zu viel verspricht, enttäuscht zuverlässig.",
"Das Leben schreibt manchmal unleserlich, aber es schreibt.",
"Wer gut kocht, hat immer Besuch.",
"Das Beste an Ferien ist alles.",
"Wer keine Fehler macht, hat keine Entscheidungen getroffen.",
"Das Leben ist fair, solange man nicht genauer hinschaut.",
"Das Beste am Wochenende ist die Abwesenheit des Montags.",
"Wer immer gewinnt, hat die falschen Gegner.",
"Das Leben ist ein Lernprojekt ohne Ende.",
"Wer zuhört, muss nicht immer antworten.",
"Ich trinke Kaffee für den Körper und Tee für die Seele.",
"Das Beste an einem Nachmittag ist, wenn er ruhig ist.",
"Wer Kompromisse macht, verliert manchmal beide Seiten.",
"Das Beste an einem guten Tag ist, dass er endet, wie er begann.",
"Wer nicht aufgibt, muss manchmal trotzdem umkehren.",
"Das Leben ist manchmal ein schlechtes Kabarett mit gutem Büffet.",
"Wer denkt, er sei fertig, hat nur aufgehört.",
"Das Beste am Dienstag ist, dass er kein Montag und kein Mittwoch ist.",
"Wer fragt, bekommt manchmal mehr als er wollte.",
"Wer spät kommt, wird manchmal am meisten begrüßt.",
"Wer viel lacht, hat eine stabile Abwehr.",
"Wer viel arbeitet, hat auch viel, worüber er klagen kann.",
"Das Beste an einem Mittwoch ist, dass die Woche zur Hälfte rum ist.",
"Ich bin kein Experte, aber ich tue so, als wäre ich einer.",
"Wer keine Grenzen hat, erschöpft sich.",
"Wer zu viel fragt, bekommt zu viele Antworten.",
"Das Beste an einer Idee ist der Moment, bevor sie scheitert.",
"Wer seinen Mut beweist, muss nicht laut davon reden.",
"Das Leben liebt Menschen, die es trotz allem schön finden.",
"Wer zufrieden ist, sucht nicht mehr.",
"Das Beste an einem langen Tag ist das warme Bett am Ende.",
"Wer denkt, er kennt alles, lernt nichts mehr.",
"Das Leben ist manchmal ein Rätsel ohne Lösungsanleitung.",
"Wer Humor einsetzt, entwaffnet fast jeden Konflikt.",
"Das Beste an einem Fehler ist, dass er gemacht wurde und nicht nur fast.",
"Wer gut schläft, ist am nächsten Tag weniger unhöflich.",
"Das Leben ist lang genug, wenn man es richtig füllt.",
"Wer andere motiviert, braucht manchmal selbst Motivation.",
"Das Beste am Herbst ist der Geruch von Regen und Zimt.",
"Wer Fehler korrigiert, wächst.",
"Wer alles kann, will manchmal gar nichts.",
"Ich habe eine Schwäche für Kaffee, Bücher und schlechte Witze.",
"Das Beste am Freitag ist sein Name.",
"Wer keine Grenzen setzt, lebt in der Grenze anderer.",
"Wer Ideen hat, braucht auch Mut.",
"Das Beste an einem Gespräch ist, wenn beide schweigen können.",
"Wer viel plant, hat selten spontane Freude.",
"Wer hilft, ohne zu fragen, ist ein Schatz.",
"Wer brüllt, hat aufgehört, zu reden.",
"Das Beste an einem Spaziergang ist, was man dabei denkt.",
"Wer das Beste gibt, bekommt nicht immer das Beste zurück.",
"Wer schweigt, stimmt manchmal zu.",
"Das Beste an einem Umweg ist das Ziel danach.",
"Wer gut erklärt, hat gut verstanden.",
"Wer immer wartet, wartet oft vergeblich.",
"Das Beste an einem Tag ist, dass er endet.",
"Wer zuhört, hat oft den Vorteil.",
"Ich bin kein Frühaufsteher, aber ich stehe früh auf, weil es nötig ist.",
"Wer viel redet, sagt manchmal zu wenig.",
"Das Beste an einem Fehler ist, wenn er einen weiterbringt.",
"Wer klug ist, lernt auch aus Fehlern anderer.",
"Wer Fragen stellt, findet Antworten.",
"Das Beste an der Ruhe ist, dass sie irgendwann kommt.",
"Wer viel lacht, hat mehr gute Momente.",
"Das Leben macht manchmal Dinge schwer, die einfach sein könnten.",
"Wer kein Ziel hat, findet keinen Weg.",
"Das Beste an einem Problem ist die Lösung.",
"Wer denkt, er habe alles gelernt, fängt wieder von vorn an.",
"Ich mache Fehler mit Stil.",
"Das Beste am Herbst sind die Äpfel und die Ausrede, drinzubleiben.",
"Wer immer lächelt, irrt sich manchmal über sein Inneres.",
"Wer Großes denkt, muss klein anfangen.",
"Das Beste an einem Abend ist, wenn er ruhig beginnt.",
"Wer zu spät kommt, hat die Ruhe vor dem Sturm.",
"Das Beste an einem langen Gespräch ist die Stille danach.",
"Das Leben liebt Menschen, die es trotz allem schön nennen.",
"Wer den Mut hat zu scheitern, hat den Mut, wirklich zu leben.",
"Das Beste am Wochenende ist die vollständige Abwesenheit von Aufgaben.",
"Wer alles aufschiebt, hat eine gut gefüllte Zukunft.",
"Wer keine Angst vor Fehlern hat, macht mehr.",
"Das Beste an einem Dienstag ist, dass die Woche noch lang ist.",
"Wer die Wahrheit sucht, findet sie manchmal am falschen Ort.",
"Wer gut lebt, fragt sich nicht ständig, was das Leben bedeutet.",
"Das Beste an einem Frühstück ist, dass es jeden Tag neu anfängt.",
"Wer immer klagt, übersieht das Gute.",
"Das Leben liebt Menschen mit Humor und Geduld.",
"Wer andere versteht, versteht sich selbst ein wenig besser.",
"Das Beste an einem schönen Wetter ist, dass es nicht dauert.",
"Wer den Mut hat zuzugeben, dass er irrt, hat gewonnen.",
"Wer lächelt und schweigt, behält meistens recht.",
"Das Beste am Warten ist, wenn es vorbei ist.",
"Wer immer pünktlich ist, hat keine Freude am Chaos.",
"Ich sage ja, meine aber oft jein.",
"Wer aufgehört hat zu lernen, hat aufgehört zu leben.",
"Das Beste an einem langen Weg ist, was man dabei sieht.",
"Wer viel gibt, bekommt manchmal viel zurück.",
"Wer vergibt, befreit sich selbst.",
"Das Beste an einem Lachen ist, dass es ansteckend ist.",
"Wer offen ist, lernt schneller.",
"Das Beste an einem Fehler ist, dass er einen neuen Weg zeigt.",
"Wer zuhört, spricht manchmal die Sprache des anderen.",
"Das Leben ist manchmal so wie es sein soll.",
"Das Beste an einem freien Tag ist die Freiheit.",
"Wer hilft, ohne zu erwarten, ist weise.",
"Das Beste an einem Ende ist der neue Anfang.",
"Wer bereit ist zu irren, ist bereit zu lernen.",
"Wer lacht, ist einen Schritt voraus.",
"Das Beste an einem Problem ist, wenn es einem hilft zu wachsen.",
"Wer viel denkt, schläft manchmal schlecht.",
"Ich bin kein Optimist, aber ich glaube an gute Tage.",
"Das Beste an einem Gespräch ist, wenn man danach mehr weiß.",
"Wer vertraut, hat Mut.",
"Das Beste an einer schlechten Erfahrung ist die Lektion.",
"Wer Freude teilt, hat mehr davon.",
"Das Leben ist manchmal lauter als man möchte.",
"Wer aufsteht, wenn er fällt, gewinnt jeden Tag.",
"Das Beste an einer Herausforderung ist das Gefühl danach.",
"Wer zuhört, versteht mehr als er erwartet.",
"Wer lacht, hat schon gewonnen.",
"Das Beste an einem Morgen ist, dass er besser als der Abend sein kann.",
"Wer schweigt, spart Energie für Wichtiges.",
"Das Leben ist manchmal genau so wie erhofft.",
"Wer Grenzen respektiert, wird respektiert.",
"Das Beste an einem guten Witz ist das Lachen danach.",
"Wer Träume verfolgt, muss manchmal umkehren.",
"Das Leben macht mehr Spaß, wenn man nicht alles so ernst nimmt.",
"Das Beste an einem regnerischen Tag ist ein gutes Buch.",
"Wer gibt, ohne zu rechnen, lebt leichter.",
"Wer keine Angst vor Stille hat, hört mehr.",
"Das Beste an einem guten Gespräch ist die Zeit danach.",
"Wer Vertrauen bricht, bricht mehr als eine Verbindung.",
"Wer hilft, wächst.",
"Das Beste am Leben ist, dass es überraschend bleibt.",
"Wer viel erlebt, hat viel zu erzählen.",
"Das Beste an einem Mittwoch ist, dass man die Wochenmitte hinter sich hat.",
"Wer klar kommuniziert, spart viele Missverständnisse.",
"Das Beste an einer neuen Woche ist der Neustart.",
"Wer Vertrauen verdient, hat es sich erarbeitet.",
"Wer sich selbst kennt, kennt seine Grenzen.",
"Das Beste an einem Neustart ist die Energie, die er bringt.",
"Wer anderen zuhört, versteht die Welt ein bisschen besser.",
"Das Leben liebt Menschen, die dankbar sind.",
"Wer fragt, zeigt Interesse.",
"Das Beste an einem Feierabend ist das Loslassen.",
"Wer zufrieden lebt, lebt gut.",
"Wer viel liest, sieht die Welt reicher.",
"Das Beste an einem ruhigen Abend ist das Gefühl danach.",
"Wer zweifelt, ist klug genug, nicht sicher zu sein.",
"Wer immer Ja sagt, erschöpft sich.",
"Wer keine Grenzen zieht, lebt in den Grenzen anderer.",
"Das Beste an einem langen Abend ist die Ruhe darin.",
"Wer täglich dankbar ist, lebt reicher.",
"Wer offen bleibt, lernt am meisten.",
"Das Beste am Lachen ist, dass es nichts kostet.",
"Wer das Gute sieht, findet mehr davon.",
"Das Leben macht manche Dinge leichter, wenn man aufhört, sie schwer zu nennen.",
"Wer Humor hat, hat eine Waffe gegen fast alles.",
"Das Beste an einem Versuch ist, dass man ihn gemacht hat.",
"Wer nie lacht, nimmt das Leben zu wörtlich.",
"Das Beste an einem neuen Tag ist, dass er noch leer ist.",
"Wer seine Stärken kennt, kann seine Schwächen managen.",
"Wer Gutes tut, fühlt sich besser.",
"Das Beste am Frühling ist das erste Sonnenlicht nach dem Winter.",
"Wer Grenzen kennt, lebt freier.",
"Das Leben liebt es, wenn man darüber lacht.",
"Das Beste an einem Dienstagnachmittag ist seine Unauffälligkeit.",
"Wer dankbar ist, sieht mehr.",
"Wer gut schläft, hat gute Gedanken am Morgen.",
"Das Beste an einem Gespräch ist das gegenseitige Verstehen.",
"Wer offen für Kritik ist, wächst schneller.",
"Das Beste an einem guten Buch ist, dass es die Zeit vergessen lässt.",
"Wer gut kommuniziert, löst Probleme bevor sie entstehen.",
"Das Beste am Leben ist, dass es täglich neu beginnt.",
"Wer Neues lernt, bleibt jung.",
"Wer lächelt, wenn es schwer ist, hat eine starke innere Basis.",
"Das Beste an einem ruhigen Sonntag ist seine Stille.",
"Wer gibt, ohne zu verlieren, hat genug.",
"Das Leben liebt Menschen, die es leicht nehmen.",
"Wer keine Fehler macht, traut sich zu wenig.",
"Das Beste an einem Abend ist die Stille danach.",
"Wer zuhört, schafft Verbindung.",
"Wer denkt, er sei perfekt, hört auf zu wachsen.",
"Das Beste an einem Fehler ist, wenn man ihn nicht wiederholt.",
"Wer Dinge wertschätzt, hat mehr davon.",
"Das Leben ist schön, wenn man es so nimmt, wie es kommt.",
"Das Beste am Mittwoch ist, dass die Wochenmitte überwunden ist.",
"Wer träumt, hat die Kraft zu beginnen.",
"Wer offen ist für Veränderung, findet neue Wege.",
"Das Beste am Freitagnachmittag ist der Freitagabend.",
"Wer vergibt, setzt sich selbst frei.",
"Wer nie aufgibt, findet irgendwann einen Weg.",
"Das Beste an einem neuen Projekt ist die erste Idee.",
"Wer lacht, macht das Beste aus dem Tag.",
"Das Leben ist schön, wenn man nicht zu viel erwartet.",
"Wer dankbar ist, findet immer etwas.",
"Das Beste am Sommer ist der Abend, wenn es abkühlt.",
"Wer liest, denkt besser.",
"Wer Neues beginnt, braucht Mut.",
"Das Beste am Herbst ist der Geruch von Erde und Regen.",
"Wer sich treu bleibt, schläft gut.",
"Das Beste an einem langen Gespräch ist das Verständnis danach.",
"Wer lächelt, macht den Tag für andere heller.",
"Das Leben liebt Menschen, die es trotz allem genießen.",
"Wer fürsorglich ist, gibt mehr als er nimmt.",
"Das Beste am Winter ist die Gemütlichkeit, die er erzwingt.",
"Wer nie zweifelt, hat keine Tiefe.",
"Das Beste an einem guten Morgen ist, dass er den Ton für den Tag setzt.",
"Wer gut zuhört, hat immer Freunde.",
"Das Leben ist reich, wenn man es durch neugierige Augen betrachtet.",
"Wer hilft ohne Erwartung, ist ein Geschenk.",
"Das Beste an einer Krise ist, was danach bleibt.",
"Wer Freude teilt, hat mehr davon.",
"Das Leben liebt Menschen, die neugierig bleiben.",
"Wer gibt was er hat, bekommt was er braucht.",
"Das Beste am Montag ist, dass er vorbeigeht.",
"Wer nicht aufgibt, findet seinen Weg.",
"Das Beste am Leben ist, dass es jeden Tag neu beginnt.",
"Wer seinen Humor behält, behält seine Menschlichkeit.",
"Das Beste am Wochenende ist das gute Gewissen am Montag.",
"Wer sich selbst versteht, versteht andere besser.",
"Das Beste an einem Fehler ist, dass er sich nicht wiederholen muss.",
"Wer offen ist, lernt täglich.",
"Das Beste am Dienstagmorgen ist seine Unauffälligkeit.",
"Wer vertraut, gewinnt meistens.",
"Das Leben liebt Menschen, die es mit Humor nehmen.",
"Wer denkt, bevor er spricht, spart sich viele Entschuldigungen.",
"Das Beste an einem langen Tag ist der Abend mit gutem Essen.",
"Wer Freude an kleinen Dingen hat, hat mehr davon.",
"Wer seinen Alltag liebt, liebt sein Leben.",
"Das Beste am Freitagnachmittag ist die Vorfreude auf das Wochenende.",
"Wer täglich aufsteht und es versucht, ist kein Versager.",
"Das Beste am Leben ist, dass man es selbst gestalten kann.",
"Wer lacht, macht das Beste aus dem Moment.",
"Das Leben ist ein langes Gespräch mit sich selbst.",
"Wer gibt und nimmt, lebt im Gleichgewicht.",
"Das Beste am Leben ist, dass es weitergeht.",
"Wer gut schläft, denkt klar.",
"Das Beste am Ende ist der neue Anfang, den es bringt.",
"Wer täglich dankbar ist, findet immer Grund zur Freude.",
"Das Beste am Leben ist seine Unberechenbarkeit.",
"Wer jeden Tag einen Schritt macht, kommt irgendwann an."
];

// 1000 Wörter (ohne Bindestriche)
export const WORD_POOL = [
"Apfel",
"Baum",
"Haus",
"Hund",
"Katze",
"Tisch",
"Stuhl",
"Buch",
"Wasser",
"Feuer",
"Luft",
"Erde",
"Licht",
"Nacht",
"Tag",
"Jahr",
"Monat",
"Woche",
"Stunde",
"Minute",
"Sekunde",
"Schule",
"Lehrer",
"Schüler",
"Bleistift",
"Papier",
"Tafel",
"Heft",
"Mappe",
"Radiergummi",
"Kaffee",
"Tee",
"Milch",
"Zucker",
"Salz",
"Brot",
"Butter",
"Käse",
"Wurst",
"Fleisch",
"Fisch",
"Gemüse",
"Obst",
"Birne",
"Banane",
"Kirsche",
"Erdbeere",
"Zitrone",
"Orange",
"Traube",
"Mango",
"Ananas",
"Melone",
"Pflaume",
"Pfirsich",
"Himbeere",
"Heidelbeere",
"Brombeere",
"Feige",
"Dattel",
"Karotte",
"Tomate",
"Gurke",
"Zwiebel",
"Knoblauch",
"Kartoffel",
"Kohl",
"Salat",
"Spinat",
"Brokkoli",
"Blumenkohl",
"Lauch",
"Sellerie",
"Paprika",
"Zucchini",
"Aubergine",
"Kürbis",
"Mais",
"Erbse",
"Bohne",
"Linse",
"Reis",
"Nudel",
"Mehl",
"Ei",
"Honig",
"Öl",
"Essig",
"Pfeffer",
"Zimt",
"Thymian",
"Basilikum",
"Petersilie",
"Rosmarin",
"Salbei",
"Minze",
"Dill",
"Koriander",
"Ingwer",
"Muskat",
"Auto",
"Fahrrad",
"Zug",
"Bus",
"Tram",
"Flugzeug",
"Schiff",
"Motorrad",
"Roller",
"Taxi",
"Strasse",
"Weg",
"Brücke",
"Tunnel",
"Ampel",
"Parkplatz",
"Bahnhof",
"Flughafen",
"Hafen",
"Haltestelle",
"Fenster",
"Tür",
"Wand",
"Boden",
"Decke",
"Dach",
"Treppe",
"Keller",
"Dachboden",
"Garage",
"Garten",
"Balkon",
"Terrasse",
"Küche",
"Bad",
"Schlafzimmer",
"Wohnzimmer",
"Esszimmer",
"Arbeitszimmer",
"Flur",
"Sofa",
"Bett",
"Schrank",
"Regal",
"Lampe",
"Spiegel",
"Vorhang",
"Teppich",
"Kissen",
"Decken",
"Computer",
"Tastatur",
"Maus",
"Bildschirm",
"Drucker",
"Scanner",
"Telefon",
"Handy",
"Tablet",
"Kamera",
"Radio",
"Fernseher",
"Lautsprecher",
"Kopfhörer",
"Kabel",
"Stecker",
"Batterie",
"Akku",
"Ladegerät",
"Speicher",
"Sonne",
"Mond",
"Stern",
"Wolke",
"Regen",
"Schnee",
"Wind",
"Sturm",
"Gewitter",
"Nebel",
"Frost",
"Eis",
"Hitze",
"Kälte",
"Frühling",
"Sommer",
"Herbst",
"Winter",
"Morgen",
"Abend",
"Norden",
"Süden",
"Osten",
"Westen",
"Berg",
"Tal",
"See",
"Fluss",
"Meer",
"Strand",
"Wald",
"Wiese",
"Feld",
"Hügel",
"Fels",
"Wüste",
"Dschungel",
"Insel",
"Küste",
"Ebene",
"Arzt",
"Krankenschwester",
"Apotheker",
"Zahnarzt",
"Optiker",
"Tierarzt",
"Feuerwehr",
"Polizei",
"Richter",
"Anwalt",
"Architekt",
"Ingenieur",
"Handwerker",
"Schreiner",
"Elektriker",
"Klempner",
"Maler",
"Schneider",
"Bäcker",
"Koch",
"Musiker",
"Schauspieler",
"Sänger",
"Tänzer",
"Sportler",
"Pilot",
"Kapitän",
"Fahrer",
"Mechaniker",
"Entwickler",
"Freude",
"Trauer",
"Angst",
"Mut",
"Liebe",
"Hass",
"Neid",
"Stolz",
"Scham",
"Wut",
"Sehnsucht",
"Hoffnung",
"Glaube",
"Zweifel",
"Vertrauen",
"Misstrauen",
"Neugier",
"Langeweile",
"Überraschung",
"Enttäuschung",
"Kraft",
"Schwäche",
"Mut",
"Feigheit",
"Weisheit",
"Dummheit",
"Güte",
"Strenge",
"Geduld",
"Ungeduld",
"Freiheit",
"Pflicht",
"Ehre",
"Würde",
"Gerechtigkeit",
"Ungerechtigkeit",
"Wahrheit",
"Lüge",
"Treue",
"Verrat",
"Singen",
"Tanzen",
"Laufen",
"Springen",
"Schwimmen",
"Schlafen",
"Essen",
"Trinken",
"Lesen",
"Schreiben",
"Lernen",
"Lehren",
"Bauen",
"Spielen",
"Arbeiten",
"Helfen",
"Reden",
"Hören",
"Sehen",
"Denken",
"Schweiz",
"Deutschland",
"Österreich",
"Frankreich",
"Italien",
"Spanien",
"Portugal",
"England",
"Niederlande",
"Belgien",
"Schweden",
"Norwegen",
"Dänemark",
"Finnland",
"Polen",
"Tschechien",
"Ungarn",
"Rumänien",
"Griechenland",
"Türkei",
"Basel",
"Zürich",
"Bern",
"Genf",
"Lausanne",
"Luzern",
"Winterthur",
"St. Gallen",
"Lugano",
"Biel",
"Berlin",
"München",
"Hamburg",
"Köln",
"Frankfurt",
"Stuttgart",
"Düsseldorf",
"Dortmund",
"Essen",
"Leipzig",
"Mathematik",
"Physik",
"Chemie",
"Biologie",
"Geschichte",
"Geografie",
"Informatik",
"Deutsch",
"Englisch",
"Französisch",
"Spanisch",
"Latein",
"Musik",
"Kunst",
"Sport",
"Ethik",
"Religion",
"Wirtschaft",
"Recht",
"Philosophie",
"Fussball",
"Basketball",
"Tennis",
"Volleyball",
"Schwimmen",
"Leichtathletik",
"Turnen",
"Reiten",
"Skifahren",
"Snowboard",
"Klettern",
"Radfahren",
"Wandern",
"Joggen",
"Yoga",
"Boxen",
"Ringen",
"Golf",
"Rugby",
"Hockey",
"Gitarre",
"Klavier",
"Geige",
"Flöte",
"Trommel",
"Trompete",
"Saxofon",
"Cello",
"Harfe",
"Kontrabass",
"Kirche",
"Schule",
"Spital",
"Museum",
"Theater",
"Kino",
"Bibliothek",
"Rathaus",
"Markt",
"Park",
"Montag",
"Dienstag",
"Mittwoch",
"Donnerstag",
"Freitag",
"Samstag",
"Sonntag",
"Januar",
"Februar",
"März",
"April",
"Mai",
"Juni",
"Juli",
"August",
"September",
"Oktober",
"November",
"Dezember",
"Neujahr",
"Löwe",
"Tiger",
"Elefant",
"Giraffe",
"Zebra",
"Nashorn",
"Nilpferd",
"Krokodil",
"Schlange",
"Schildkröte",
"Vogel",
"Adler",
"Falke",
"Eule",
"Papagei",
"Pinguin",
"Flamingo",
"Pferd",
"Kuh",
"Schwein",
"Schaf",
"Ziege",
"Huhn",
"Ente",
"Gans",
"Truthahn",
"Hase",
"Fuchs",
"Wolf",
"Bär",
"Einheit",
"Gruppe",
"Klasse",
"Team",
"Familie",
"Freund",
"Kollege",
"Partner",
"Nachbar",
"Fremder",
"Erwachsener",
"Kind",
"Jugendlicher",
"Rentner",
"Vater",
"Mutter",
"Bruder",
"Schwester",
"Grossvater",
"Grossmutter",
"Frühstück",
"Mittagessen",
"Abendessen",
"Snack",
"Dessert",
"Suppe",
"Salat",
"Hauptgang",
"Vorspeise",
"Nachspeise",
"Löffel",
"Gabel",
"Messer",
"Teller",
"Schüssel",
"Glas",
"Tasse",
"Kanne",
"Topf",
"Pfanne",
"Schule",
"Gymnasium",
"Berufsschule",
"Universität",
"Hochschule",
"Kindergarten",
"Hort",
"Ausbildung",
"Studium",
"Abschluss",
"Zeitung",
"Magazin",
"Buch",
"Roman",
"Gedicht",
"Brief",
"Nachricht",
"Bericht",
"Kommentar",
"Interview",
"Schlüssel",
"Schloss",
"Vorhängeschloss",
"Tresor",
"Kasse",
"Geldbeutel",
"Bankkarte",
"Münze",
"Schein",
"Quittung",
"Frieden",
"Krieg",
"Konflikt",
"Einigung",
"Abkommen",
"Vertrag",
"Gesetz",
"Regel",
"Vorschrift",
"Ausnahme",
"Lehrplan",
"Stundentafel",
"Zeugnis",
"Note",
"Prüfung",
"Aufgabe",
"Hausaufgabe",
"Projekt",
"Präsentation",
"Referat",
"Werkzeug",
"Hammer",
"Nagel",
"Schraubenzieher",
"Zange",
"Säge",
"Bohrmaschine",
"Schrauben",
"Dübel",
"Klebstoff",
"Gesicht",
"Auge",
"Ohr",
"Nase",
"Mund",
"Wange",
"Kinn",
"Stirn",
"Haar",
"Bart",
"Hand",
"Arm",
"Schulter",
"Rücken",
"Brust",
"Bauch",
"Bein",
"Fuss",
"Finger",
"Zeh",
"Sommer",
"Urlaub",
"Ferien",
"Reise",
"Ausflug",
"Wanderung",
"Camping",
"Strand",
"Gebirge",
"Stadtbesichtigung",
"Farbe",
"Rot",
"Blau",
"Grün",
"Gelb",
"Orange",
"Lila",
"Rosa",
"Braun",
"Schwarz",
"Weiss",
"Grau",
"Silber",
"Gold",
"Türkis",
"Beige",
"Dunkelblau",
"Hellgrün",
"Dunkrot",
"Mintgrün",
"Kissen",
"Decke",
"Bettlaken",
"Kopfkissen",
"Matratze",
"Lattenrost",
"Bettwäsche",
"Vorhang",
"Jalousie",
"Rolllade",
"Unterricht",
"Lektion",
"Einheit",
"Thema",
"Kapitel",
"Abschnitt",
"Übung",
"Lösung",
"Ergebnis",
"Antwort",
"Firma",
"Betrieb",
"Unternehmen",
"Abteilung",
"Büro",
"Sitzung",
"Konferenz",
"Besprechung",
"Protokoll",
"Agenda",
"Mütze",
"Schal",
"Handschuh",
"Jacke",
"Mantel",
"Hose",
"Rock",
"Hemd",
"Bluse",
"Pullover",
"Socke",
"Schuh",
"Stiefel",
"Sandal",
"Turnschuh",
"Unterwäsche",
"Gürtel",
"Krawatte",
"Brille",
"Uhr",
"Tanne",
"Buche",
"Eiche",
"Birke",
"Ahorn",
"Weide",
"Fichte",
"Kiefer",
"Kastanie",
"Linde",
"Rose",
"Tulpe",
"Narzisse",
"Sonnenblume",
"Lilie",
"Margerite",
"Lavendel",
"Jasmin",
"Veilchen",
"Vergissmeinnicht",
"Tintenstift",
"Kugelschreiber",
"Füllfeder",
"Marker",
"Textmarker",
"Lineal",
"Geodreieck",
"Zirkel",
"Schere",
"Klebeband",
"Hoffnung",
"Traum",
"Ziel",
"Weg",
"Schritt",
"Fortschritt",
"Erfolg",
"Misserfolg",
"Versuch",
"Entscheidung",
"Daten",
"Datei",
"Ordner",
"Archiv",
"Sicherung",
"Passwort",
"Netzwerk",
"Server",
"Cloud",
"Software",
"Elch",
"Rentier",
"Biber",
"Otter",
"Dachs",
"Igel",
"Eichhörnchen",
"Maulwurf",
"Fledermaus",
"Luchs",
"Montag",
"Bericht",
"Feedback",
"Aufgabe",
"Termin",
"Frist",
"Verantwortung",
"Entlastung",
"Delegation",
"Zustimmung",
"Norden",
"Süden",
"Westen",
"Osten",
"Aufgang",
"Untergang",
"Horizont",
"Aussicht",
"Perspektive",
"Blickwinkel",
"Klima",
"Umwelt",
"Natur",
"Energie",
"Ressource",
"Recycling",
"Nachhaltigkeit",
"Abfall",
"Kompost",
"Bepflanzung",
"Geschichte",
"Legende",
"Mythos",
"Sage",
"Fabel",
"Märchen",
"Roman",
"Krimi",
"Drama",
"Komödie",
"Alphabet",
"Buchstabe",
"Silbe",
"Wort",
"Satz",
"Abschnitt",
"Absatz",
"Text",
"Sprache",
"Dialekt",
"Feld",
"Wiese",
"Weide",
"Weinberg",
"Obstgarten",
"Gemüsegarten",
"Gewächshaus",
"Scheune",
"Stall",
"Hof",
"Rätsel",
"Frage",
"Antwort",
"Problem",
"Lösung",
"Herausforderung",
"Schwierigkeit",
"Chance",
"Risiko",
"Sicherheit",
"Gitarre",
"Lied",
"Melodie",
"Rhythmus",
"Takt",
"Ton",
"Klang",
"Stille",
"Echo",
"Gesang",
"Hunger",
"Durst",
"Appetit",
"Genuss",
"Geschmack",
"Geruch",
"Gefühl",
"Berührung",
"Sicht",
"Gehör",
"Idee",
"Plan",
"Konzept",
"Strategie",
"Taktik",
"Methode",
"System",
"Prozess",
"Ablauf",
"Ergebnis",
"Schmetterling",
"Käfer",
"Ameise",
"Biene",
"Wespe",
"Libelle",
"Grille",
"Mücke",
"Spinne",
"Wurm",
"Buch",
"Kapitel",
"Seite",
"Zeile",
"Wort",
"Titel",
"Autor",
"Verlag",
"Inhalt",
"Vorwort",
"Reise",
"Ziel",
"Strecke",
"Tempo",
"Pause",
"Aufenthalt",
"Ankunft",
"Abfahrt",
"Rückreise",
"Erlebnis",
"Gesundheit",
"Krankheit",
"Heilung",
"Medizin",
"Behandlung",
"Diagnose",
"Symptom",
"Therapie",
"Erholung",
"Vorsorge",
"Schönheit",
"Eleganz",
"Einfachheit",
"Komplexität",
"Harmonie",
"Balance",
"Kontrast",
"Dynamik",
"Stärke",
"Ausdauer",
"Hütte",
"Chalet",
"Villa",
"Apartment",
"Wohngemeinschaft",
"Unterkunft",
"Hotel",
"Pension",
"Hostel",
"Campingplatz",
"Zahlen",
"Messen",
"Vergleichen",
"Analysieren",
"Planen",
"Organisieren",
"Strukturieren",
"Verwalten",
"Koordinieren",
"Kommunizieren",
"Pflege",
"Fürsorge",
"Respekt",
"Achtsamkeit",
"Toleranz",
"Empathie",
"Mitgefühl",
"Offenheit",
"Ehrlichkeit",
"Aufmerksamkeit",
"Konzentration",
"Fokus",
"Überblick",
"Detailblick",
"Zusammenfassung",
"Ausblick",
"Rückblick",
"Einblick",
"Durchblick",
"Tiefgang",
"Bild",
"Foto",
"Zeichnung",
"Gemälde",
"Skizze",
"Grafik",
"Karte",
"Diagramm",
"Tabelle",
"Schema",
"Leistung",
"Fähigkeit",
"Kompetenz",
"Potenzial",
"Entwicklung",
"Wachstum",
"Reife",
"Erfahrung",
"Wissen",
"Können",
"Wohnort",
"Heimat",
"Herkunft",
"Zugehörigkeit",
"Gemeinschaft",
"Gesellschaft",
"Kultur",
"Tradition",
"Brauchtum",
"Identität",
"Fantasie",
"Kreativität",
"Vorstellung",
"Intuition",
"Inspiration",
"Improvisation",
"Spontaneität",
"Neugier",
"Entdeckung",
"Erkundung",
"Zusammenarbeit",
"Teamwork",
"Unterstützung",
"Begleitung",
"Kooperation",
"Koordination",
"Austausch",
"Dialog",
"Vernetzung",
"Verbindung",
"Ehrgeiz",
"Disziplin",
"Konsequenz",
"Beharrlichkeit",
"Engagement",
"Einsatz",
"Hingabe",
"Passion",
"Begeisterung",
"Entschlossenheit",
"Kasse",
"Rechnung",
"Bon",
"Rabatt",
"Preis",
"Angebot",
"Bestellung",
"Lieferung",
"Rückgabe",
"Garantie",
"Freiraum",
"Grenzen",
"Verantwortung",
"Freiheit",
"Pflicht",
"Recht",
"Möglichkeit",
"Entscheidung",
"Wahlmöglichkeit",
"Konsequenz",
"Bildschirm",
"Tastatur",
"Eingabe",
"Ausgabe",
"Benutzer",
"Interface",
"Programm",
"Applikation",
"Datenbank",
"Algorithmus",
"Würfel",
"Ball",
"Rad",
"Dreieck",
"Viereck",
"Kreis",
"Linie",
"Punkt",
"Fläche",
"Volumen"
];
